server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:${PICTURE_BROWSER_DB:/data/db/pb}
    username: sa
    password: poiuytQWE123!
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true

picture-browser:
  groups: "${PICTURE_BROWSER_ROOT:{'default':'/data/pictures','picture2':'/data/pictures2'}}"