authorizeRequests:
  antMatchers:
    - /public/**: permitAll
    - /admin/**: hasRole('ADMIN')
    - /user/**: hasRole('USER')
    - /api/**: hasAnyRole('ADMIN', 'USER')
    - /private/**: authenticated()

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/openai-proxy